### PR TITLE
Choose monitor with GTK dialog

### PR DESCRIPTION
**Pull request by ben-grande**
Fixes: https://github.com/QubesOS/qubes-issues/issues/9282

### CODE REVIEW

**Comment by ben-grande** [comment]
@marmarta Can you please take a look?

**Comment by marmarta** [comment]
I like it with one problem - the select monitor window I got was very small, with enough space to see just one screen, and I had to scroll to see the other (at first glance I thought it wasn't working at all).

qvc

**Comment by ben-grande** [comment]
@marmarta That is a zenity dialog relevant to another PR:

- https://github.com/QubesOS/qubes-video-companion/pull/24

Which I thought I had done a good conditional size estimate, but I tested only on Debian and your Personal qube Zentiy program looks like Fedora. So Debian and Fedora Zenity behave differently. Anyway, please checkout the code relevant to this PR.

**Comment by marmarta** [comment]
yeah, you're right... I'm learning to use qubes builder v2 and sometimes I end up with things switching to main when I wanted to test something, it's one of those times :/

**Comment by ben-grande** [comment]
Ok, I don't encounter this issue when I cancel on Dom0. My second monitor only appears listed in Dom0, my DomUs only list `DUMMY0`.

But your error happens with me when I call the script directly from the target emulating a call:
```sh
QREXEC_REMOTE_DOMAIN=disp1360 /usr/share/qubes-video-companion/sender/screenshare.py
```
```python3
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 170, in <module>
    screenshare = ScreenShare()
                  ^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 26, in __init__
    self.main(self)
  File "/usr/share/qubes-video-companion/sender/service.py", line 155, in main
    self.start_transmission()
  File "/usr/share/qubes-video-companion/sender/service.py", line 124, in start_transmission
    width, height, fps, extra_params = self.parameters()
                                       ^^^^^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 121, in parameters
    raise ValueError("Monitor index was not set")
ValueError: Monitor index was not set
```

Note that the following already happened before:
```python3
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 82, in <module>
    main(sys.argv)
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 17, in main
    width, height, fps = read_video_parameters()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 63, in read_video_parameters
    raise RuntimeError("wrong number of bytes read")
RuntimeError: wrong number of bytes read
```

Now the `ValueError("Monitor index was not set")` only appears when emulating the call while the receiver now handles input with 0 bytes as an operation canceled by the sender.

Pushed changes.

**Comment by marmarta** [comment]
PipelineRetry

**Review by marmarta — APPROVED** [review]

**Comment by ben-grande** [comment]
Thanks for the review guys!

**Pull request merged**
