### PR TITLE
Suppress deprecation warnings of Gdk.Screen.height

### PR DESCRIPTION
**Pull request by Augsch123**
Fix https://github.com/QubesOS/qubes-issues/issues/8454

I've tested this is working fine with one-screen setup. Unfortunately I don't have a multi-screen setup to test this. @Minimalist73 would you like to test this to make sure it won't cause regression?

### CODE REVIEW

**Comment by Minimalist73** [comment]
Just tested this with Fedora-38, Debian-11 and Debian-12. For each, I get this error message:
```
(screenshare.py:2645): Gdk-CRITICAL **: 16:40:06.141: gdk_atom_intern: assertion 'atom_name != NULL' failed

(screenshare.py:2645): Gdk-CRITICAL **: 16:40:06.142: gdk_atom_intern: assertion 'atom_name != NULL' failed
Receiving video stream at 1920x1080 30 FPS...
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 78, in <module>
    screenshare = ScreenShare()
                  ^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 24, in __init__
    self.main(self)
  File "/usr/share/qubes-video-companion/sender/service.py", line 158, in main
    self.start_transmission()
  File "/usr/share/qubes-video-companion/sender/service.py", line 128, in start_transmission
    element = self._element = Gst.parse_launchv(
                              ^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gst_parse_error: could not link queue0 to capsfilter0 (3)
```

So yes, it seems to cause a regression.

**Comment by Augsch123** [comment]
Just fixed a typo, should be better now ( I hope so )

**Comment by marmarek** [comment]
@Minimalist73 is it better now?
@Augsch123 plase add fix issue reference to the commit message too

**Comment by marmarek** [comment]
PipelineRetry

**Comment by Minimalist73** [comment]
I still get the same error:
```
(screenshare.py:1257): Gdk-CRITICAL **: 10:39:14.608: gdk_atom_intern: assertion 'atom_name != NULL' failed

(screenshare.py:1257): Gdk-CRITICAL **: 10:39:14.609: gdk_atom_intern: assertion 'atom_name != NULL' failed
Receiving video stream at 1920x1080 30 FPS...
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 78, in <module>
    screenshare = ScreenShare()
                  ^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 24, in __init__
    self.main(self)
  File "/usr/share/qubes-video-companion/sender/service.py", line 158, in main
    self.start_transmission()
  File "/usr/share/qubes-video-companion/sender/service.py", line 128, in start_transmission
    element = self._element = Gst.parse_launchv(
                              ^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gst_parse_error: could not link queue0 to capsfilter0 (3)
```

**Comment by Minimalist73** [comment]
I changed this part of the code with "-" instead of "+":

```
"crop_right": monitor.x - monitor.width,
"crop_bottom": monitor.y - monitor.height,
```

It works, but I get this message now:
```
/usr/share/qubes-video-companion/sender/service.py:128: Warning: value "4294967216" of type 'guint' is invalid or out of range for property 'endy' of type 'guint'
  element = self._element = Gst.parse_launchv(
```

**Comment by Augsch123** [comment]
That's weird. I'm thinking that fixing this problem is beyond my capability ( especially when lacking a proper testing environment ). So I'll close this PR. Sorry for taking your precious time to review this.

**Pull request closed without merging**
